Route code execution through Auth server
CS3219-AY2324S1/ay2324s1-course-assessment-g37 pull request #60
Opened 2023-11-07 10:28 UTC by randallnhr

2023-11-07 10:32 UTC, gohyongjing approved these changes
LGTM! Very clean interface between front-end, auth server and code execution server

2023-11-07 11:02 UTC, rexcyrio requested changes

2023-11-08 09:15 UTC, randallnhr commented on microservices/auth/src/server.ts
> +  } catch (error) {
I have made it such that the output box will display the error returned.

2023-11-08 09:45 UTC, rexcyrio approved these changes
LGTM :+1:

2023-11-08 09:45 UTC, merged